"""
Multi-Tier Wallet Manager
=========================

Implements hot / warm / cold wallet architecture with:
- Automated rebalancing between tiers
- Per-tier transaction limits
- Watermark-based alerts
- Sweep excess from hot → warm → cold
- Refill requests from cold → warm → hot

All operations are audit-logged via Redis and the LedgerService.
"""

import json
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from decimal import Decimal
from enum import Enum
from typing import Dict, List, Optional, Any
from uuid import uuid4

import redis.asyncio as aioredis

from casino.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


# ---------------------------------------------------------------------------
# Domain Types
# ---------------------------------------------------------------------------

class WalletTier(str, Enum):
    HOT = "hot"
    WARM = "warm"
    COLD = "cold"


class TransferStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class WalletBalance:
    """Snapshot of a single currency's balance across all tiers."""
    currency: str
    hot: Decimal = Decimal("0")
    warm: Decimal = Decimal("0")
    cold: Decimal = Decimal("0")

    @property
    def total(self) -> Decimal:
        return self.hot + self.warm + self.cold

    def to_dict(self) -> Dict[str, str]:
        return {
            "currency": self.currency,
            "hot": str(self.hot),
            "warm": str(self.warm),
            "cold": str(self.cold),
            "total": str(self.total),
        }


@dataclass
class TransferRequest:
    """A request to move funds between wallet tiers."""
    id: str = field(default_factory=lambda: str(uuid4()))
    from_tier: str = ""
    to_tier: str = ""
    currency: str = ""
    amount: str = "0"
    reason: str = ""
    status: str = TransferStatus.PENDING.value
    requested_by: str = "system"
    approved_by: Optional[str] = None
    created_at: str = ""
    completed_at: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class WalletAlert:
    """Alert generated by the wallet manager."""
    id: str = field(default_factory=lambda: str(uuid4()))
    severity: str = AlertSeverity.WARNING.value
    message: str = ""
    currency: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    resolved: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Wallet Manager
# ---------------------------------------------------------------------------

class MultiTierWalletManager:
    """
    Manages hot / warm / cold wallet tiers for each supported currency.

    State is stored in Redis so that it survives restarts and is accessible
    by multiple workers.  Keys:

    - ``wallet:balance:{currency}:{tier}`` – Decimal balance string
    - ``wallet:transfers``                 – sorted-set of transfer IDs (by ts)
    - ``wallet:transfer:{id}``             – JSON hash of TransferRequest
    - ``wallet:alerts``                    – list of WalletAlert JSON
    - ``wallet:daily_withdrawal``          – daily withdrawal counter
    """

    # Supported currencies
    CURRENCIES = ["BTC", "ETH", "SOL", "USDT", "USDC", "LTC"]

    def __init__(self, redis_client: aioredis.Redis):
        self.redis = redis_client
        self.cfg = settings.wallet

    # ------------------------------------------------------------------
    # Balance helpers
    # ------------------------------------------------------------------

    def _bkey(self, currency: str, tier: WalletTier) -> str:
        return f"wallet:balance:{currency}:{tier.value}"

    async def get_tier_balance(self, currency: str, tier: WalletTier) -> Decimal:
        raw = await self.redis.get(self._bkey(currency, tier))
        return Decimal(raw) if raw else Decimal("0")

    async def set_tier_balance(self, currency: str, tier: WalletTier, amount: Decimal) -> None:
        await self.redis.set(self._bkey(currency, tier), str(amount))

    async def get_balance(self, currency: str) -> WalletBalance:
        hot = await self.get_tier_balance(currency, WalletTier.HOT)
        warm = await self.get_tier_balance(currency, WalletTier.WARM)
        cold = await self.get_tier_balance(currency, WalletTier.COLD)
        return WalletBalance(currency=currency, hot=hot, warm=warm, cold=cold)

    async def get_all_balances(self) -> List[WalletBalance]:
        return [await self.get_balance(c) for c in self.CURRENCIES]

    async def get_total_bankroll(self) -> Dict[str, Decimal]:
        """Total bankroll per currency (sum of all tiers)."""
        totals: Dict[str, Decimal] = {}
        for cur in self.CURRENCIES:
            bal = await self.get_balance(cur)
            totals[cur] = bal.total
        return totals

    # ------------------------------------------------------------------
    # Daily withdrawal tracking
    # ------------------------------------------------------------------

    async def record_withdrawal(self, currency: str, amount: Decimal) -> None:
        key = f"wallet:daily_withdrawal:{currency}"
        current = Decimal(await self.redis.get(key) or "0")
        new_total = current + amount
        # Reset daily counter at midnight (TTL until end-of-day)
        ttl = await self.redis.ttl(key)
        if ttl < 0:
            ttl = 86400  # 24h default
        await self.redis.set(key, str(new_total), ex=ttl if ttl > 0 else 86400)

    async def get_daily_withdrawals(self, currency: str) -> Decimal:
        raw = await self.redis.get(f"wallet:daily_withdrawal:{currency}")
        return Decimal(raw) if raw else Decimal("0")

    # ------------------------------------------------------------------
    # Limit checks
    # ------------------------------------------------------------------

    async def check_withdrawal_allowed(
        self, currency: str, amount: Decimal
    ) -> tuple[bool, str]:
        """
        Verify that a withdrawal can be served by the hot wallet.

        Returns (allowed, reason).
        """
        # Single withdrawal limit
        if amount > Decimal(str(self.cfg.hot_wallet_single_withdrawal_limit)):
            return False, (
                f"Amount {amount} exceeds single withdrawal limit "
                f"({self.cfg.hot_wallet_single_withdrawal_limit})"
            )

        # Daily cap
        daily = await self.get_daily_withdrawals(currency)
        if daily + amount > Decimal(str(self.cfg.daily_withdrawal_limit)):
            return False, (
                f"Daily withdrawal limit reached "
                f"({daily + amount} > {self.cfg.daily_withdrawal_limit})"
            )

        # Hot wallet capacity
        hot = await self.get_tier_balance(currency, WalletTier.HOT)
        if hot < amount:
            return False, (
                f"Hot wallet insufficient ({hot} < {amount}). "
                "A refill from warm storage may be required."
            )

        return True, "OK"

    # ------------------------------------------------------------------
    # Rebalancing
    # ------------------------------------------------------------------

    async def check_watermarks(self, currency: str) -> List[WalletAlert]:
        """
        Evaluate low / high watermark thresholds for the hot wallet
        and return any generated alerts.
        """
        bal = await self.get_balance(currency)
        alerts: List[WalletAlert] = []
        now = datetime.utcnow().isoformat()

        if bal.total == 0:
            return alerts

        hot_pct = bal.hot / bal.total if bal.total else Decimal("0")

        # ── LOW WATERMARK ──
        # Hot wallet has dropped below 1% of total — needs refill
        low_threshold = Decimal(str(self.cfg.low_watermark_multiplier)) * Decimal("0.05")
        if hot_pct < low_threshold and bal.warm > 0:
            refill_target = bal.total * Decimal(str(self.cfg.hot_wallet_max_percent))
            refill_amount = min(refill_target - bal.hot, bal.warm)
            if refill_amount > 0:
                alert = WalletAlert(
                    severity=AlertSeverity.WARNING.value,
                    message=f"Hot wallet low ({hot_pct:.2%} of total). Auto-requesting refill of {refill_amount} {currency}.",
                    currency=currency,
                    details={
                        "hot_pct": f"{hot_pct:.4f}",
                        "refill_amount": str(refill_amount),
                    },
                    created_at=now,
                )
                alerts.append(alert)
                # Auto-create transfer request
                await self.create_transfer(
                    from_tier=WalletTier.WARM,
                    to_tier=WalletTier.HOT,
                    currency=currency,
                    amount=refill_amount,
                    reason="auto_low_watermark",
                )

        # ── HIGH WATERMARK ──
        # Hot wallet exceeds target allocation — sweep excess to warm
        high_threshold = Decimal(str(self.cfg.high_wallet_max_percent)) if hasattr(self.cfg, "high_wallet_max_percent") else Decimal(str(self.cfg.hot_wallet_max_percent)) * Decimal("2")
        if hot_pct > high_threshold:
            target = bal.total * Decimal(str(self.cfg.hot_wallet_max_percent))
            excess = bal.hot - target
            if excess > 0:
                alert = WalletAlert(
                    severity=AlertSeverity.INFO.value,
                    message=f"Hot wallet high ({hot_pct:.2%}). Sweeping {excess} {currency} to warm.",
                    currency=currency,
                    details={
                        "hot_pct": f"{hot_pct:.4f}",
                        "excess": str(excess),
                    },
                    created_at=now,
                )
                alerts.append(alert)
                await self.create_transfer(
                    from_tier=WalletTier.HOT,
                    to_tier=WalletTier.WARM,
                    currency=currency,
                    amount=excess,
                    reason="auto_high_watermark_sweep",
                )

        # Persist alerts
        for a in alerts:
            await self.redis.lpush("wallet:alerts", json.dumps(a.to_dict()))

        return alerts

    async def run_rebalance_check(self) -> List[WalletAlert]:
        """Run watermark checks for every currency. Returns all alerts."""
        all_alerts: List[WalletAlert] = []
        for cur in self.CURRENCIES:
            all_alerts.extend(await self.check_watermarks(cur))
        return all_alerts

    # ------------------------------------------------------------------
    # Internal transfers (between tiers)
    # ------------------------------------------------------------------

    async def create_transfer(
        self,
        from_tier: WalletTier,
        to_tier: WalletTier,
        currency: str,
        amount: Decimal,
        reason: str = "",
        requested_by: str = "system",
    ) -> TransferRequest:
        """Create a pending transfer between wallet tiers."""
        now = datetime.utcnow()
        tr = TransferRequest(
            from_tier=from_tier.value,
            to_tier=to_tier.value,
            currency=currency,
            amount=str(amount),
            reason=reason,
            requested_by=requested_by,
            created_at=now.isoformat(),
        )

        # Auto-approve hot↔warm transfers
        if {from_tier, to_tier} <= {WalletTier.HOT, WalletTier.WARM}:
            tr.status = TransferStatus.APPROVED.value
            tr.approved_by = "auto"

        pipe = self.redis.pipeline()
        pipe.set(f"wallet:transfer:{tr.id}", json.dumps(tr.to_dict()))
        pipe.zadd("wallet:transfers", {tr.id: now.timestamp()})
        await pipe.execute()

        logger.info(
            f"Wallet transfer created: {tr.id} | {from_tier.value} → {to_tier.value} "
            f"| {amount} {currency} | status={tr.status}"
        )
        return tr

    async def get_transfer(self, transfer_id: str) -> Optional[TransferRequest]:
        raw = await self.redis.get(f"wallet:transfer:{transfer_id}")
        if not raw:
            return None
        data = json.loads(raw)
        return TransferRequest(**data)

    async def list_transfers(
        self, status: Optional[str] = None, limit: int = 50
    ) -> List[Dict[str, Any]]:
        ids = await self.redis.zrevrange("wallet:transfers", 0, limit - 1)
        results: List[Dict[str, Any]] = []
        for tid in ids:
            raw = await self.redis.get(f"wallet:transfer:{tid}")
            if raw:
                data = json.loads(raw)
                if status and data.get("status") != status:
                    continue
                results.append(data)
        return results

    async def execute_transfer(self, transfer_id: str, executor: str = "system") -> Dict[str, Any]:
        """
        Execute an approved transfer — move funds between tiers atomically.

        For cold-wallet transfers this would trigger a blockchain
        transaction; here we update the in-memory (Redis) balances.
        """
        tr = await self.get_transfer(transfer_id)
        if not tr:
            return {"success": False, "error": "Transfer not found"}

        if tr.status not in (TransferStatus.APPROVED.value, TransferStatus.PENDING.value):
            return {"success": False, "error": f"Transfer status is {tr.status}, cannot execute"}

        from_tier = WalletTier(tr.from_tier)
        to_tier = WalletTier(tr.to_tier)
        amount = Decimal(tr.amount)

        # Verify source balance
        src = await self.get_tier_balance(tr.currency, from_tier)
        if src < amount:
            tr.status = TransferStatus.FAILED.value
            await self.redis.set(f"wallet:transfer:{tr.id}", json.dumps(tr.to_dict()))
            return {"success": False, "error": f"Insufficient {from_tier.value} balance ({src} < {amount})"}

        # Move atomically via pipeline
        pipe = self.redis.pipeline()
        pipe.set(self._bkey(tr.currency, from_tier), str(src - amount))

        dst = await self.get_tier_balance(tr.currency, to_tier)
        pipe.set(self._bkey(tr.currency, to_tier), str(dst + amount))

        tr.status = TransferStatus.COMPLETED.value
        tr.completed_at = datetime.utcnow().isoformat()
        tr.approved_by = tr.approved_by or executor
        pipe.set(f"wallet:transfer:{tr.id}", json.dumps(tr.to_dict()))
        await pipe.execute()

        logger.info(f"Transfer {tr.id} executed: {amount} {tr.currency} {from_tier.value} → {to_tier.value}")

        return {"success": True, "transfer": tr.to_dict()}

    async def approve_and_execute_transfer(
        self, transfer_id: str, approver: str
    ) -> Dict[str, Any]:
        """Approve a pending transfer and execute it immediately."""
        tr = await self.get_transfer(transfer_id)
        if not tr:
            return {"success": False, "error": "Transfer not found"}
        if tr.status != TransferStatus.PENDING.value:
            return {"success": False, "error": f"Transfer status is {tr.status}"}

        tr.status = TransferStatus.APPROVED.value
        tr.approved_by = approver
        await self.redis.set(f"wallet:transfer:{tr.id}", json.dumps(tr.to_dict()))
        return await self.execute_transfer(transfer_id, executor=approver)

    # ------------------------------------------------------------------
    # Alerts
    # ------------------------------------------------------------------

    async def get_alerts(self, limit: int = 50, unresolved_only: bool = True) -> List[Dict[str, Any]]:
        raw_list = await self.redis.lrange("wallet:alerts", 0, limit - 1)
        alerts = [json.loads(r) for r in raw_list]
        if unresolved_only:
            alerts = [a for a in alerts if not a.get("resolved")]
        return alerts

    # ------------------------------------------------------------------
    # Reserve ratio
    # ------------------------------------------------------------------

    async def get_reserve_ratio(self, user_liabilities: Dict[str, Decimal]) -> Dict[str, Any]:
        """
        Compute reserve ratio: total wallet assets / total user liabilities.

        *user_liabilities* is a mapping of ``{currency: total_owed}``.
        """
        ratios: Dict[str, Any] = {}
        for cur in self.CURRENCIES:
            bal = await self.get_balance(cur)
            liability = user_liabilities.get(cur, Decimal("0"))
            ratio = (bal.total / liability) if liability > 0 else None
            ratios[cur] = {
                "total_assets": str(bal.total),
                "total_liabilities": str(liability),
                "ratio": f"{ratio:.4f}" if ratio is not None else "N/A",
                "solvent": ratio >= Decimal("1") if ratio is not None else True,
            }
        return ratios

    # ------------------------------------------------------------------
    # Deposit routing
    # ------------------------------------------------------------------

    async def route_deposit(self, currency: str, amount: Decimal) -> WalletTier:
        """
        Decide which tier receives the deposit.

        Small / medium deposits go to hot wallet (immediate liquidity).
        Large deposits route directly to warm.
        """
        hot = await self.get_tier_balance(currency, WalletTier.HOT)
        bal = await self.get_balance(currency)
        hot_target = bal.total * Decimal(str(self.cfg.hot_wallet_max_percent)) if bal.total else amount

        if hot + amount <= hot_target * Decimal("1.5"):
            # Hot wallet still under 1.5x target — deposit here
            await self.set_tier_balance(currency, WalletTier.HOT, hot + amount)
            return WalletTier.HOT
        else:
            # Route to warm
            warm = await self.get_tier_balance(currency, WalletTier.WARM)
            await self.set_tier_balance(currency, WalletTier.WARM, warm + amount)
            return WalletTier.WARM

    async def process_withdrawal_from_hot(self, currency: str, amount: Decimal) -> bool:
        """Deduct from hot wallet balance after a withdrawal is approved."""
        hot = await self.get_tier_balance(currency, WalletTier.HOT)
        if hot < amount:
            return False
        await self.set_tier_balance(currency, WalletTier.HOT, hot - amount)
        await self.record_withdrawal(currency, amount)
        return True
